import { Injectable } from '@angular/core';
import { QuestEvent } from '../models/questEvent';
import { SearchCriteria } from '../models/searchCriteria';
import { Observable, Subject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  private events: QuestEvent[] = [
    {
        "Region": "Central",
        "Category": "Fairs/Festivals",
        "StartDate": "1/4/2020",
        "EndDate": "1/5/2020",
        "Title": "Worthington Historical Society Antiques Show",
        "Description": "High-quality wares will be offered for sale from across the Midwest and Northeast. Exhibitors to bring city, country and painted furniture as well as items randing from stoneware to decoys to antique dolls to estate and costume jewelry.  No reproductions ",
        "Venue": "Holiday Inn Hotel, Worthington",
        "Address": "7007 N. High St.",
        "City": "Worthingotn",
        "Phone": "614/885-1247",
        "Website": "worthingtonhistory.org",
        "Time": "Sat. 10 a.m.�5 p.m.; Sun. 11 a.m.�4 p.m.",
        "Price": "$8"
    },
    {
        "Region": "Central",
        "Category": "Fairs/Festivals",
        "StartDate": "1/17/2020",
        "EndDate": "1/17/2020",
        "Title": "Columbus Winter Beerfest",
        "Description": "Get your drink on with more than 250 craft beers, with proceeds benefiting the Big Joe Duskin Music Foundation and the Columbus Jazz Arts Group.",
        "Venue": "Columbus Convention Center",
        "Address": "400 N. High St.",
        "City": "Columbus",
        "Phone": "",
        "Website": "columbusbeerfest.com",
        "Time": "7 p.m.",
        "Price": "$35 advance, $45 day of, $45 advance VIP, $55 VIP day of event."
    },
    {
        "Region": "Central",
        "Category": "Museums/Galleries",
        "StartDate": "8/23/2019",
        "EndDate": "1/4/2020",
        "Title": "George Bellows and the American Experience",
        "Description": "This exhibit showcases the vibrant, groundbreaking work of one of the finest artists America has ever produced in a show not to be missed.",
        "Venue": "Columbus Museum of Art",
        "Address": "480 E. Broad St.",
        "City": "Columbus",
        "Phone": "614/221-6801",
        "Website": "columbusmuseum.org",
        "Time": "Tues.�Sun. 10 a.m.�5:30 p.m., Thur. 10 a.m.�8:30 p.m.",
        "Price": "Adults $12; seniors 60 and over and students 18 and up (with ID) $8; students 6�17 $5; children 5 and under, members and Sun. free"
    },
    {
        "Region": "Central",
        "Category": "Museums/Galleries",
        "StartDate": "9/21/2019",
        "EndDate": "1/5/2020",
        "Title": "Curious George: Let's Get Curious!",
        "Description": "Curious George: Let's Get Curious, will introduce young children to Curious George's world and lead visitors on a fun and interactive math, science and engineering-based adventure.",
        "Venue": "COSI",
        "Address": "333 W Broad St",
        "City": "Columbus",
        "Phone": "614/228-2674",
        "Website": "cosi.org",
        "Time": "Wed.�Sat. 10 a.m.�5 p.m., Sun. noon�6 p.m.",
        "Price": "$12.95�$17.95"
    },
    {
        "Region": "Central",
        "Category": "Museums/Galleries",
        "StartDate": "11/8/2019",
        "EndDate": "2/16/2020",
        "Title": "Think Outside the Brick",
        "Description": "Artists use Lego brand building blocks to demonstrate the remendous creative capacity of the blocks.",
        "Venue": "Columbus Museum of Art",
        "Address": "480 E. Broad St.",
        "City": "Columbus",
        "Phone": "614/221-6801",
        "Website": "columbusmuseum.org/",
        "Time": "Tues.�Sun. 10 a.m.�5:30 p.m., Thur. 10 a.m.�8:30 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Central",
        "Category": "Museums/Galleries",
        "StartDate": "11/15/2019",
        "EndDate": "3/9/2020",
        "Title": "Matthew Brandt: Photographs ",
        "Description": "Brandt pushes the boundaries of photography by embedding unexpected elements, from bubblegum to dust, for a bold, playful outcome.",
        "Venue": "Columbus Museum of Art",
        "Address": "480 E. Broad St.",
        "City": "Columbus",
        "Phone": "614/221-6801",
        "Website": "columbusmuseum.org",
        "Time": "Tues.�Sun. 10 a.m.�5:30 p.m., Thur. 10 a.m.�8:30 p.m. ",
        "Price": "Call for prices."
    },
    {
        "Region": "Central",
        "Category": "Museums/Galleries",
        "StartDate": "7/13/2019",
        "EndDate": "7/13/2020",
        "Title": "1950s: Building the American Dream",
        "Description": "Experience the 1950s through the eyes of a family living in central Ohio as you walk through their Lustron home. Step back in time and explore the nooks and crannies, cupboards and drawers of the family's real, full-size house, built right inside the muse",
        "Venue": "Ohio History Center",
        "Address": "800 E. 17th Ave.",
        "City": "Columbus",
        "Phone": "614/297-2300",
        "Website": "ohiohistory.org",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Central",
        "Category": "Music/Theater",
        "StartDate": "1/4/2020",
        "EndDate": "1/4/2020",
        "Title": "Edwin Butler",
        "Description": "Swing by the holiday jazz performance if you are visiting the conservatory.",
        "Venue": "Franklin Park Conservatory",
        "Address": "1777 E. Broad St.",
        "City": "Columbus",
        "Phone": "614/715-8000",
        "Website": "fpconservatory.org",
        "Time": "2 p.m.",
        "Price": "Free with admission."
    },
    {
        "Region": "Central",
        "Category": "Music/Theater",
        "StartDate": "1/17/2020",
        "EndDate": "1/18/2020",
        "Title": "A Concert to End Homelessness",
        "Description": "Columbus Jazz Orchestra partners with the Community Shelter Board for an inspiring evening of big band jazz, song and dance to raise awareness and funds for the homeless in central Ohio.",
        "Venue": "Capitol Theatre at the Vern Riffe Center",
        "Address": "77 S. High St.",
        "City": "Columbus",
        "Phone": "614/460-7214",
        "Website": "jazzartsgroup.org",
        "Time": "8 p.m.",
        "Price": "$35"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "12/4/2019",
        "EndDate": "1/1/2020",
        "Title": "State Auto's Christmas Corner",
        "Description": "State Auto opens the nativity display to the public.",
        "Venue": "State Auto Insurance",
        "Address": "518 E. Broad St.",
        "City": "Columbus",
        "Phone": "614/464-5000",
        "Website": "facebook.com/christmascorner",
        "Time": "5:30 p.m. � 12:30 a.m.",
        "Price": "Free"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "12/6/2019",
        "EndDate": "1/11/2020",
        "Title": "Grand Illumination",
        "Description": "Celebrate the season as Downtown Columbus comes alive during the holidays. Stroll along the illuminated Scioto Mile Promenade to Bicentennial Park where visitors can enjoy the stunning holiday lights. The Scioto Mile features more than 200,000 holiday lig",
        "Venue": "Bicentennial Park",
        "Address": "233 S. Civic Center Dr.",
        "City": "Columbus",
        "Phone": "614/645-7995",
        "Website": "sciotomile.com",
        "Time": "Dusk to Dawn",
        "Price": "Free"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "11/20/2019",
        "EndDate": "1/26/2020",
        "Title": "Rocky Mountain Express",
        "Description": "\nfont-family: \"&#65325;&#65331; &#26126;&#26397;\";\n}@font-face {\nfont-family: \"Cambria Math\";\n}@font-face {\nfont-family: \"Calibri\";\n}@font-face {\nfont-family: \"Cambria\";\n}p.MsoNormal, li.MsoNormal, div.MsoNormal { margin: 0in 0in 0.0001pt; font-size: 12pt",
        "Venue": "COSI",
        "Address": "333 W. Broad St.",
        "City": "Columbus",
        "Phone": "614/228-2674",
        "Website": "cosi.org",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "9/25/2019",
        "EndDate": "2/8/2020",
        "Title": "Bruce Munro: Light at Franklin Park Conservatory",
        "Description": "Light up the night with 10 large-scale light installations and gallery works that transform the conservatory's indoor biomes and outdoor courtyards into an enchanting experience.",
        "Venue": "Franklin Park Conservatory",
        "Address": "1777 E. Broad St.",
        "City": "Columbus",
        "Phone": "614/645-8733",
        "Website": "fpconservatory.org",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "12/31/2019",
        "EndDate": "1/1/2020",
        "Title": "Marion Pop-n-Drop",
        "Description": "Watch the large \"popcorn\" ball, enhanced with fireworks, drop at the stroke of midnight. Free hot chocolate and activities in the APEX Kidz Center from 10 p.m. to midnight.",
        "Venue": "Chase Bank Parking Lot",
        "Address": "West of Center and Prospect streets",
        "City": "Marion",
        "Phone": "740/382-2181",
        "Website": "downtownmarion.com",
        "Time": "11:30 p.m �12:30 a.m.",
        "Price": "Free"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "1/26/2020",
        "EndDate": "1/26/2020",
        "Title": "Clear Channel Marion Bridal Extravaganza 2020",
        "Description": "Booths on display will help you complete many of your wedding needs.",
        "Venue": "Marion County Fairgrounds",
        "Address": "220 E. Fairground St.",
        "City": "Marion",
        "Phone": "740/383-1131",
        "Website": "wmrn.com",
        "Time": "1 p.m.�4 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "1/30/2020",
        "EndDate": "1/30/2020",
        "Title": "Firesdie Chats - Ohio-Bound: The Harding Family Migration",
        "Description": "The program will be held in Guthery Room and presented by the Harding Home Presidential Site.",
        "Venue": "Ohio State University Marion",
        "Address": "1465 Mt. Vernon Ave.",
        "City": "Marion",
        "Phone": "740/387-9630",
        "Website": "hardinghome.org",
        "Time": "7 p.m.",
        "Price": "$10�$25 for all three programs."
    },
    {
        "Region": "Northeast",
        "Category": "Fairs/Festivals",
        "StartDate": "12/31/2019",
        "EndDate": "1/1/2020",
        "Title": "First Night Akron",
        "Description": "First Night Akron is a New Year's Eve celebration unlike any other. This family-friendly, alcohol-free celebration of the arts brings the community together to enjoy indoor entertainment and fun throughout downtown Akron.",
        "Venue": "Downtown",
        "Address": "103 S. High St.",
        "City": "Akron",
        "Phone": "330/374-7676",
        "Website": "firstnightakron.org",
        "Time": "6 p.m.�12 a.m.",
        "Price": "$10"
    },
    {
        "Region": "Northeast",
        "Category": "Fairs/Festivals",
        "StartDate": "1/18/2020",
        "EndDate": "1/18/2020",
        "Title": "Chardon Winter Fest",
        "Description": "Have fun with the whole family, including carriage rides, dog sled demonstrations, ice sculpture and an outside snow maze.",
        "Venue": "Downtown",
        "Address": "Short Court Street",
        "City": "Chardon",
        "Phone": "",
        "Website": "chardontomorrow.org",
        "Time": "9 a.m.�2 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Northeast",
        "Category": "Museums/Galleries",
        "StartDate": "6/1/2019",
        "EndDate": "1/5/2020",
        "Title": "Titanic: The Artifact Exhibition",
        "Description": "Discover the compelling human stories told through authentic artifacts and recreations of the ship�s interior in \"Titanic: The Artifact Exhibition.\"",
        "Venue": "Great Lakes Science Center",
        "Address": "601 Erieside Ave.",
        "City": "Cleveland",
        "Phone": "216/694-2000",
        "Website": "greatscience.com",
        "Time": "Call for times.",
        "Price": "Adults $24, children 2�12 $22"
    },
    {
        "Region": "Northeast",
        "Category": "Museums/Galleries",
        "StartDate": "5/24/2019",
        "EndDate": "3/1/2020",
        "Title": "Rolling Stones: 50 Years of Satisfaction",
        "Description": "The first comprehensive exhibit of the Rolling Stones highlights their 50-year history with recordings, artifacts, film, interactive exhibits and programs.",
        "Venue": "Rock and Roll Hall of Fame & Museum",
        "Address": "1100 Rock and Roll Blvd.",
        "City": "Cleveland",
        "Phone": "216/781-7625",
        "Website": "rockhall.com",
        "Time": "10 a.m.�5:30 p.m., Wed. until 9 p.m.",
        "Price": "Adults $22, seniors $17, children 9�12 $13, children under 9 free"
    },
    {
        "Region": "Northeast",
        "Category": "Music/Theater",
        "StartDate": "12/4/2019",
        "EndDate": "1/5/2020",
        "Title": "Wicked",
        "Description": "Learn the true story of the so-called wicked witch with emerald green skin long before that girl from Kansas arrived in Munchkinland.",
        "Venue": "State Theatre",
        "Address": "1519 Euclid Ave.",
        "City": "Cleveland",
        "Phone": "216/241-6000",
        "Website": "playhousesquare.org",
        "Time": "Call for times.",
        "Price": "$30�$175"
    },
    {
        "Region": "Northeast",
        "Category": "Music/Theater",
        "StartDate": "1/10/2020",
        "EndDate": "2/2/2020",
        "Title": "Yentl",
        "Description": "A young woman defies convention and the laws of her people to fulfill her dream. Disguised as a young man, she becomes a brilliant student � and the most wanted bachelor in town.",
        "Venue": "Allen Theatre at PlayhouseSquare",
        "Address": "1407 Euclid Ave.",
        "City": "Cleveland",
        "Phone": "216/241-6000",
        "Website": "clevelandplayhouse.com/main-stage/2019-2020/yentl",
        "Time": "Check website for times.",
        "Price": "$15�$69"
    },
    {
        "Region": "Northeast",
        "Category": "Music/Theater",
        "StartDate": "1/18/2020",
        "EndDate": "1/18/2020",
        "Title": "Josh Turner - in concert",
        "Description": "Country superstar Josh Turner has earned numerous CMA, ACM and Grammy nominations since the release of his debut album, \"Long Black Train.\" He has sold more than five million albums and garnered four No. 1 hits.",
        "Venue": "Stambaugh Auditorium",
        "Address": "1000 Fifth Ave.",
        "City": "Youngstown",
        "Phone": "330/259-0555",
        "Website": "stambaughauditorium.com",
        "Time": "8 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northeast",
        "Category": "Music/Theater",
        "StartDate": "1/26/2020",
        "EndDate": "1/26/2020",
        "Title": "Symphony in Step",
        "Description": "Created by Maestro Randall Craig Fleischer and Step Afrika, \"Symphony In Step\" is the first ever merger of stepping and classical music. The mesmerizing display of physical movement and eloquent music will leave you amazed at the troupe's power, strength,",
        "Venue": "Powers Auditorium - DeYor Performing Arts Center",
        "Address": "260 W. Federal St.",
        "City": "Youngstown",
        "Phone": "330/744-0264",
        "Website": "youngstownsymphony.com",
        "Time": "4 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "1/1/2020",
        "EndDate": "1/1/2020",
        "Title": "New Year's Day Rock 'n' Roll Pajama Party Brunch at The Ritz-Carlton",
        "Description": "Roll over to MUSE in your PJs and slippers to start off 2020 in the city that rocks with a brunch buffet, Bloody Mary Bar and a roaming rock 'n' roll guitarist. Reservations are recommended.",
        "Venue": "The Ritz-Carlton, Cleveland",
        "Address": "1515 W. Third St.",
        "City": "Cleveland",
        "Phone": "216/902-5255",
        "Website": "ritzcarlton.com/en/Properties/Cleveland/Information/Calendar/Default.htm",
        "Time": "Seatings from 10 a.m.–2:30 p.m.",
        "Price": "$65 per adult, $20 per child"
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "1/3/2020",
        "EndDate": "1/3/2020",
        "Title": "MIX: Celebrate",
        "Description": "Celebrate the museum's monumental expansion and renovation project at the monthly art, music and cocktail event, featuring Solstice favorite DJ Rekha.",
        "Venue": "Cleveland Museum of Art",
        "Address": "11150 East Blvd.",
        "City": "Cleveland",
        "Phone": "216/421-7350",
        "Website": "clevelandart.org",
        "Time": "5�11 p.m.",
        "Price": "Members $7, $9 day of event, nonmembers $14, $16 day of event."
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "1/17/2020",
        "EndDate": "1/18/2020",
        "Title": "Northeast Ohio Sportsman Show",
        "Description": "Large Sportsman's Expo offering everything of interest to today's hunter, angler, trapper, archer, boater and hiker. Seminars taught by nationally known hunting and fishing experts. Indoor competitions include archery, tag and bow baseball.",
        "Venue": "Buckeye Event Center",
        "Address": "624 Henry St.",
        "City": "Dalton",
        "Phone": "740/397-7788",
        "Website": "ohiosportsmanshow.com",
        "Time": "Fri. 9 a.m.�8 p.m., Sat. 9 a.m.�6 p.m.",
        "Price": "Adults $10, kids 12 & under free. Two day pass $15."
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "1/29/2020",
        "EndDate": "1/29/2020",
        "Title": "Harlem Globetrotters 2020 World Tour",
        "Description": "For 90-plus minutes, the Globetrotters exhibit a captivating assortment of trick shots, high-flying dunks and precise timing, all with a side-splitting array of comedy guaranteed to entertain both the young and young at heart.",
        "Venue": "Covelli Centre",
        "Address": "229 E. Front St.",
        "City": "Youngstown",
        "Phone": "330/746-5600",
        "Website": "covellicentre.com",
        "Time": "7 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "1/31/2020",
        "EndDate": "2/1/2020",
        "Title": "Toughest Monster Truck Tour",
        "Description": "The Toughest Monster Truck Tour is returning to the Covelli Centre. The big trucks on the dirt track are back with 6 monster trucks in the wheelie, racing and freestyle competition including Bigfoot, Overboard and Toxic.",
        "Venue": "Covelli Centre",
        "Address": "229 E. Front St.",
        "City": "Youngstown",
        "Phone": "330/746-5600",
        "Website": "covellicentre.com",
        "Time": "7:30 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northwest",
        "Category": "Fairs/Festivals",
        "StartDate": "1/10/2020",
        "EndDate": "1/11/2020",
        "Title": "Island Days",
        "Description": "Enjoy Lake Erie Island entertainment and specialties (lobster bisque and Brandy Alexanders) in downtown Sandusky. Happy hour at the Sandusky State Theatre Saturday evening.",
        "Venue": "Downtown Sandusky",
        "Address": "Columbus Avenue",
        "City": "Sandusky",
        "Phone": "800/625-5269",
        "Website": "steinhospice.org",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northwest",
        "Category": "Museums/Galleries",
        "StartDate": "10/4/2019",
        "EndDate": "1/1/2020",
        "Title": "Fresh Impressions: Early Modern Japanese Prints",
        "Description": "Landmark exhibitions introduced modern Japanese prints to America in the 1930s. This exhibition reassembles and reinterprets those shows and adds companion objects depicted in the 343 prints such as kimonos, ancient armor, samurai swords and a Japanese ro",
        "Venue": "Toledo Museum of Art",
        "Address": "2445 Monroe St.",
        "City": "Toledo",
        "Phone": "419/255-8000",
        "Website": "toledomuseum.org",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northwest",
        "Category": "Museums/Galleries",
        "StartDate": "10/17/2019",
        "EndDate": "4/13/2020",
        "Title": "Rutherford B. Hayes: Buckeye President",
        "Description": "This exclusive new exhibit tells the story of Hayes' life and how he created The Ohio State University.",
        "Venue": "Hayes Presidential Center",
        "Address": "Spiegel Grove",
        "City": "Fremont",
        "Phone": "419/332-2081",
        "Website": "rbhayes.org",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "1/12/2020",
        "EndDate": "1/12/2020",
        "Title": "What A Character",
        "Description": "Favorite children's book characters come to life through music and verse.",
        "Venue": "Valentine Theatre",
        "Address": "410 Adams St.",
        "City": "Toledo",
        "Phone": "419/246-8000",
        "Website": "toledosymphony.com",
        "Time": "3 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "1/17/2020",
        "EndDate": "1/17/2020",
        "Title": "Waltzing Through Vienna",
        "Description": "Celebrate the New Year with a delightful program of Viennese and Parisian classics. Jennifer Frautschi returns for two crowd-pleasing violin show pieces.",
        "Venue": "Peristyle at the Toledo Museum of Art",
        "Address": "2445 Monroe St.",
        "City": "Toledo",
        "Phone": "419/246-8000",
        "Website": "toledosymphony.com",
        "Time": "8 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "1/18/2020",
        "EndDate": "1/19/2020",
        "Title": "Stomp",
        "Description": "This international sensation passes on conventional percussive instruments to use matchboxes, wooden poles, brooms, garbage cans and hubcaps to fill the stage with magnificent rhythms.",
        "Venue": "Stranahan Theater",
        "Address": "4645 Heatherdowns Blvd.",
        "City": "Toledo",
        "Phone": "419/381-8851",
        "Website": "theaterleague.com/toledo/stomp/",
        "Time": "Call for times.",
        "Price": "Starts at $28."
    },
    {
        "Region": "Northwest",
        "Category": "Other Events",
        "StartDate": "1/26/2020",
        "EndDate": "1/26/2020",
        "Title": "GIANT AutoParts SWAP Meet",
        "Description": "Auto parts, tools, literature, garage items and much more will be up for grabs.",
        "Venue": "Allen County Fairgrounds",
        "Address": "2750 Harding Hwy.",
        "City": "Lima",
        "Phone": "419/331-3837",
        "Website": "",
        "Time": "8 a.m.�3 p.m.",
        "Price": "$5"
    },
    {
        "Region": "Southeast",
        "Category": "Museums/Galleries",
        "StartDate": "11/30/2019",
        "EndDate": "1/4/2020",
        "Title": "Looking Through The Sky: Landscape Paintings by Michael McEwan",
        "Description": "McEwan is one of Ohio's preeminent painters of the landscape. He blends his familiarity with art history with contemporary emphasis on mark-making and abstraction.",
        "Venue": "Zanesville Museum of Art",
        "Address": "620 Military Rd.",
        "City": "Zanesville",
        "Phone": "740/452-0741",
        "Website": "zanesvilleart.org",
        "Time": "Wed., Fri. & Sat. 10 a.m.�5 p.m.; Thur. 10 a.m.�7:30 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Southeast",
        "Category": "Museums/Galleries",
        "StartDate": "9/20/2019",
        "EndDate": "1/5/2020",
        "Title": "A Space in Time: Works by Donald Roberts",
        "Description": "Organic form, color and ambiguous space are �pushed and pulled� to experimental and expressive limits, revealing Roberts' strong relationship with nature. ",
        "Venue": "Kennedy Museum of Art",
        "Address": "Lin Hall, Ohio University",
        "City": "Lin Hall, Ohio University",
        "Phone": "740/593-1305",
        "Website": "ohio.edu/museum",
        "Time": "Call for times.",
        "Price": "Free"
    },
    {
        "Region": "Southeast",
        "Category": "Museums/Galleries",
        "StartDate": "9/6/2019",
        "EndDate": "1/12/2020",
        "Title": "The Trisolini Print Project",
        "Description": "The exhibit complements Prints from the Permanent Collection Selected by Donald Roberts.",
        "Venue": "Kennedy Museum of Art",
        "Address": "Lin Hall, Ohio University",
        "City": "Lin Hall, Ohio University",
        "Phone": "740/593-1305",
        "Website": "ohio.edu/museum",
        "Time": "Call for times.",
        "Price": "Free"
    },
    {
        "Region": "Southeast",
        "Category": "Museums/Galleries",
        "StartDate": "8/23/2019",
        "EndDate": "2/23/2020",
        "Title": "Navajo Saddle Blankets",
        "Description": "The history of navajo weaving has produced objects from wearing blankets to floor rugs to wall hangings. The Navajo saddle blankets in the exhibit include rare examples of Germantown Sunday Saddle Blankets from the late 1800s and early 1900s and more.",
        "Venue": "Kennedy Museum of Art",
        "Address": "Lin Hall, Ohio University",
        "City": "Athens",
        "Phone": "740/593-1305",
        "Website": "ohio.edu/museum",
        "Time": "Call for times.",
        "Price": "Free"
    },
    {
        "Region": "Southeast",
        "Category": "Museums/Galleries",
        "StartDate": "1/17/2020",
        "EndDate": "3/16/2020",
        "Title": "Ohio University School of Art & Design Faculty Exhibition",
        "Description": "This biennial exhibition showcases original artwork by faculty ranging from paiting and sculpture to graphic design and video art.",
        "Venue": "Kennedy Museum of Art",
        "Address": "Lin Hall, Ohio University",
        "City": "Athens",
        "Phone": "740/593-1305",
        "Website": "ohio.edu/museum",
        "Time": "Call for times.",
        "Price": "Free"
    },
    {
        "Region": "Southeast",
        "Category": "Museums/Galleries",
        "StartDate": "1/17/2020",
        "EndDate": "5/4/2020",
        "Title": "Improvisations: Jazz Photographs by Herman Leonard",
        "Description": "The 1947 Ohio University graduate is known for his unique images of jazz icons such as Miles Davis, James Moody, Billie Holiday, Sarah Vaughan and Chet Baker.",
        "Venue": "Kennedy Museum of Art",
        "Address": "Lin Hall, Ohio University",
        "City": "Athens",
        "Phone": "740/593-1305",
        "Website": "ohio.edu/museum",
        "Time": "Call for times.",
        "Price": "Free"
    },
    {
        "Region": "Southeast",
        "Category": "Music/Theater",
        "StartDate": "1/3/2020",
        "EndDate": "1/4/2020",
        "Title": "Sherlock Holmes Murder Mystery Weekend",
        "Description": "The game's afoot! Attendees will participate in a suspense-filled encounter with world-renowned detective Sherlock Holmes as he and Watson become embroiled in murder and mystery. The grand prize is $250.",
        "Venue": "St. Benedict's Social Hall",
        "Address": "714 Gomber Ave.",
        "City": "Cambridge",
        "Phone": "800/933-5480",
        "Website": "visitguernseycounty.com",
        "Time": "Begins Friday at 7:30 p.m.",
        "Price": "Packages start at $480 per couple, lodging included"
    },
    {
        "Region": "Southeast",
        "Category": "Music/Theater",
        "StartDate": "1/26/2020",
        "EndDate": "1/26/2020",
        "Title": "The Grascals",
        "Description": "The bluegrass bands has three Grammy nominations and was named Bluegrass Band of the Year. See why for yourself.",
        "Venue": "Stuart's Opera House",
        "Address": "52 Public Square",
        "City": "Nelsonville",
        "Phone": "740/753-1924",
        "Website": "stuartsoperahouse.org",
        "Time": "3 p.m.",
        "Price": "$20�$30"
    },
    {
        "Region": "Southeast",
        "Category": "Other Events",
        "StartDate": "11/1/2019",
        "EndDate": "1/4/2020",
        "Title": "Dickens Victorian Village Themed Weekends",
        "Description": "Create a memory that will last a lifetime during Dickens Victorian Village. Themed weekends include Desperate for Downtown Weekend, Queen Victoria Weekend and It�s a Wonderful World of Dickens, just to name a few.",
        "Venue": "Historic Downtown Cambridge",
        "Address": "643 Wheeling Ave.",
        "City": "Cambridge",
        "Phone": "866/334-6446",
        "Website": "dickensvictorianvillage.com",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Southeast",
        "Category": "Other Events",
        "StartDate": "1/3/2020",
        "EndDate": "1/3/2020",
        "Title": "2020 Bridal Fair",
        "Description": "The Ariel will be full of wedding related vendors for brides, grooms and their friends to view the facility and exhibits.",
        "Venue": "Ariel Ann Carson Dater Performing Arts Center",
        "Address": "426 Second Ave.",
        "City": "Gallipolis",
        "Phone": "740/446-ARTS",
        "Website": "arieltheatre.org",
        "Time": "Noon�4 p.m.",
        "Price": "$5"
    },
    {
        "Region": "Southeast",
        "Category": "Other Events",
        "StartDate": "1/18/2020",
        "EndDate": "1/18/2020",
        "Title": "Winter Hike at Hocking Hills",
        "Description": "Hiking in Hocking Hills is beautiful any time of year. Join the pack this winter.",
        "Venue": "Old Man's Cave Visitor's Center",
        "Address": "18905 St. Rte. 664 S.",
        "City": "Logan",
        "Phone": "740/385-6841",
        "Website": "",
        "Time": "Continuous starts 9�11 a.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "8/24/2019",
        "EndDate": "1/5/2020",
        "Title": "A Buckeye Abroad",
        "Description": "Frank Wilcox's watercolors portraying Paris during the Belle Epoque are on display for the first time in a museum setting.",
        "Venue": "The Dayton Art Institute",
        "Address": "456 Belmonte Park N.",
        "City": "Dayton",
        "Phone": "937/223-5277",
        "Website": "daytonartinstitute.org",
        "Time": "Tues.�Fri. 11 a.m.�8 p.m., Sat. 10 a.m.�5 p.m., Sun. 12�5 p.m.",
        "Price": "Adults $8, seniors $5, children 17 and under free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "9/10/2019",
        "EndDate": "1/5/2020",
        "Title": "Eugene Atget: Picturing Paris",
        "Description": "Lose yourself in the ebauty of Old Paris with this selection of more than 20 rare prints from the founder of documentary photography.",
        "Venue": "The Dayton Art Institute",
        "Address": "456 Belmonte Park N.",
        "City": "Dayton",
        "Phone": "937/223-5277",
        "Website": "daytonartinstitute.org",
        "Time": "Tues.�Fri. 11 a.m.�8 p.m., Sat. 10 a.m.�5 p.m., Sun. 12�5 p.m.",
        "Price": "Adults $8, seniors $5, children 17 and under free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "10/26/2019",
        "EndDate": "1/5/2020",
        "Title": "Object of Devotion & Elizabeth Turk: Wings",
        "Description": "Object of Devotion features 60 beautiful alabaster sculptures from London's Victoria and Albert Museum. In Conjunction, DAI will also exhibit works by contemporary marble sculptor Elizabeth Turk.\nfont-family: \"Cambria Math\";\n}@font-face {\nfont-family: \"Ca",
        "Venue": "The Dayton Art Institute",
        "Address": "456 Belmonte Park N.",
        "City": "Dayton",
        "Phone": "937/223-4278",
        "Website": "daytonartinstitute.org",
        "Time": "Tues.�Fri. 11 a.m.�8 p.m., Sat. 10 a.m.�5 p.m., Sun. noon�5 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "11/8/2019",
        "EndDate": "1/5/2020",
        "Title": "Antique Christmas at the Taft Museum of Art",
        "Description": "This annual display is a treat for children of all ages, with Christmas trees, vintage dolls, ornaments and decorations set up throughout the historic house, as well aso vintage Christmas-themed magazine covers and calendars.",
        "Venue": "Taft Museum of Art",
        "Address": "316 Pike St.",
        "City": "Cincinnati",
        "Phone": "513/241-0343",
        "Website": "taftmuseum.org",
        "Time": "Wed.�Sun. 11 a.m.�5 p.m.",
        "Price": "Adults $10, seniors and students $8, children 12�17 $4, children under 12 free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "9/20/2019",
        "EndDate": "1/12/2020",
        "Title": "Telling Tales: Stories and Legends in 19th Century American Art",
        "Description": "Spanning from the Colonial period through the Civil War, 46 paintings and seven sculptures highlight the American fascination with narrative art. The exhibition includes paintings by giants of early 19th-century American art as well as others being shown ",
        "Venue": "Taft Museum of Art",
        "Address": "316 Pike St.",
        "City": "Cincinnati",
        "Phone": "513/241-0343",
        "Website": "taftmuseum.org",
        "Time": "Wed.�Sun. 11 a.m.�5 p.m.",
        "Price": "Adults $10, seniors and students $8, children 12�17 $4, children under 12 free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "9/7/2019",
        "EndDate": "1/19/2020",
        "Title": "What's New: Fashion and Contemporary Craft",
        "Description": "This exhibition will showcase 26 recent additions to the museum�s permanent collection in the areas of fashion and craft. These works, all created since 1950, will be paired to highlight shared affinities that document the diverse trends, ideas, events an",
        "Venue": "Cincinnati Museum of Art",
        "Address": "953 Eden Park Dr.",
        "City": "Cincinnati",
        "Phone": "513/721-ARTS",
        "Website": "cincinnatiartmuseum.org",
        "Time": "Tues.�Sun. 11 a.m.�5 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "10/26/2019",
        "EndDate": "1/19/2020",
        "Title": "Degas, Renoir and Poetic Pastels",
        "Description": "From Alfred Sisley to Degas to Odilon Redon, this exhibition will highlight the bold achievements of French artists working with pastels in the second half of the 19th century. ",
        "Venue": "Cincinnati Museum of Art",
        "Address": "953 Eden Park Dr.",
        "City": "Cincinnati",
        "Phone": "513/721-ARTS",
        "Website": "cincinnatiartmuseum.org",
        "Time": "Tues.�Sun. 11 a.m.�5 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "9/21/2019",
        "EndDate": "2/2/2020",
        "Title": "JR",
        "Description": "This exhibition celebrates the breadth and ambition of what world-renowned French artist JR dubs \"Pervasive Art.\" It reflects his interventions by way of wheat pasted images, photography, video projections, a large sculpture as well as an interactive phot",
        "Venue": "Contemporary Arts Center",
        "Address": "44 E. 6th St.",
        "City": "Cincinnati",
        "Phone": "513/345-8400",
        "Website": "contemporaryartscenter.org",
        "Time": "Mon. 10 a.m.�9 p.m., Wed.�Fri. 10 a.m.�6 p.m., Sat.�Sun. 11 a.m.�6 p.m.",
        "Price": "Adults $7.50, seniors and students $5.50, children under 5 free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "10/12/2019",
        "EndDate": "2/27/2020",
        "Title": "Bricks, Barrel Vaults and Beer: The Architectural Legacy of Cincinnati Breweries",
        "Description": "Explore the influence of technology on the function and construction of breweries, their architectural styles, examine their impact on the city's built environment and present ideas for the future of the buildings.",
        "Venue": "The Betts House",
        "Address": "416 Clark St.",
        "City": "Cincinnati",
        "Phone": "513/651-0734",
        "Website": "thebettshouse.org",
        "Time": "Call for times.",
        "Price": "$2"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "11/23/2019",
        "EndDate": "3/2/2020",
        "Title": "Elizabeth Nourse: Rites of Passage",
        "Description": "This exhibition celebrates the acquisition of The First Communion (La premi�re communion), a masterpiece by Cincinnati-native Elizabeth Nourse (1859�1938).",
        "Venue": "Cincinnati Museum of Art",
        "Address": "953 Eden Park Dr.",
        "City": "Cincinnati",
        "Phone": "513/721-ARTS",
        "Website": "cincinnatiartmuseum.org",
        "Time": "Tues.�Sun. 11 a.m.�5 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "1/11/2020",
        "EndDate": "1/11/2020",
        "Title": "Phil Dirt & The Dozers",
        "Description": "With their musical talent, high energy and contagious sense of humor, Phil Dirt & The Dozers will transport you to the '50s, '60s and '70s and help you recapture those wonderful days.",
        "Venue": "Murphy Theatre",
        "Address": "50 W. Main St.",
        "City": "Wilmington",
        "Phone": "877/274-3848",
        "Website": "themurphytheatre.org",
        "Time": "7:30 p.m.",
        "Price": "$22.50"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "1/26/2020",
        "EndDate": "1/26/2020",
        "Title": "Cosmos: CCO + Exhale Dance Tribe",
        "Description": "Continuing the 40th season, Exhale Dance Tribe joins the CCO to propel you on a journey from Chaos to Order, and through Suffering toward Salvation, evoking the evolution of the Cosmos and the promise of eternity. Cutting edge movement meets masterful mus",
        "Venue": "School for Creative & Performing Arts",
        "Address": "108 W. Central Parkway",
        "City": "Cincinnati",
        "Phone": "513/723-1182",
        "Website": "ccocincinnati.org",
        "Time": "4 p.m.",
        "Price": "$25, $10"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "1/26/2020",
        "EndDate": "1/26/2020",
        "Title": "The Sounds of Stan Getz",
        "Description": "Delight in this annual collaboration where jazz and orchestra meet, featuring the cool rhythms of the bossa nova.",
        "Venue": "Patricia Corbett Theater",
        "Address": "University of Cincinnati",
        "City": "Cincinnati",
        "Phone": "513/556-4183",
        "Website": "ccm.uc.edu",
        "Time": "7 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Southwest",
        "Category": "Other Events",
        "StartDate": "11/29/2019",
        "EndDate": "1/1/2020",
        "Title": "Clifton Mill Holiday Lights",
        "Description": "Clifton Mill celebrates the Christmas season with an extraordinary light display of 3.5 million lights illuminating the mill, the gorge, the riverbanks, trees and bridges.",
        "Venue": "Clifton Mill",
        "Address": "75 Water St.",
        "City": "Clifton",
        "Phone": "937/767-5501",
        "Website": "cliftonmill.com",
        "Time": "5�9:30 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Other Events",
        "StartDate": "11/30/2019",
        "EndDate": "1/5/2020",
        "Title": "Snowland",
        "Description": "Imagine a warm, enchanting place where it snows indoors and happiness reigns.",
        "Venue": "Great Wolf Lodge",
        "Address": "2501 Great Wolf Dr.",
        "City": "Mason",
        "Phone": "513/459-8885",
        "Website": "greatwolf.com",
        "Time": "10 a.m.�10 p.m.",
        "Price": "Included with your stay at Great Wolf Lodge in Mason"
    },
    {
        "Region": "Southwest",
        "Category": "Other Events",
        "StartDate": "11/30/2019",
        "EndDate": "1/26/2020",
        "Title": "And There Were Animals: World Nativity Traditions",
        "Description": "See 150 nativities from around the world shown in three new themed exhibits and selected from a collection of nearly 3,000. Attend the grand opening Nov. 30 that includes the exhibits, entertainment, refreshments, children's activities, shopping in the St",
        "Venue": "University of Dayton Libraries",
        "Address": "300 College Park",
        "City": "Dayton",
        "Phone": "937/229-4094",
        "Website": "udayton.edu/libraries/manger",
        "Time": "1�5 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Central",
        "Category": "Fairs/Festivals",
        "StartDate": "2/8/2020",
        "EndDate": "2/8/2020",
        "Title": "Avant-Garde Art & Craft Show - Columbus",
        "Description": "Get the perfect gift for Valentine's Day and enjoy a day out on the town. This large show will feature nearly 100 artists and crafters selling their original handmade items.",
        "Venue": "St. Agatha Church (Parish Hall)",
        "Address": "1860 Northam Rd.",
        "City": "Columbus",
        "Phone": "440/227-8794",
        "Website": "avantgardeshows.com",
        "Time": "10 a.m.�4 p.m.",
        "Price": "Adults $3, children under 12 are free."
    },
    {
        "Region": "Central",
        "Category": "Museums/Galleries",
        "StartDate": "2/6/2020",
        "EndDate": "5/1/2020",
        "Title": "Toulouse-Lautrec and La Vie Modern: Paris 1880-1910",
        "Description": "Through the work of avant-garde Parisian artists, this exhibit investigates a generation of artists continuing the battle against French Academic standards.",
        "Venue": "Columbus Museum of Art",
        "Address": "480 E. Broad St.",
        "City": "Columbus",
        "Phone": "614/221-6801",
        "Website": "columbusmuseum.org",
        "Time": "Tues.�Sun. 10 a.m.�5:30 p.m., Thur. 10 a.m.�8:30 p.m.",
        "Price": ""
    },
    {
        "Region": "Central",
        "Category": "Music/Theater",
        "StartDate": "2/7/2020",
        "EndDate": "2/15/2020",
        "Title": "BalletMet's Alice in Wonderland",
        "Description": "Follow Alice down the rabbit hole into a land of mayhem and magic in Gerard Charles' \"Alice in Wonderland.\" Whether you're big or you're small you'll find that logic is no match for madness among the delirious denizens of Wonderland.",
        "Venue": "The Capitol Theatre",
        "Address": "77 S. High St.",
        "City": "Columbus",
        "Phone": "614/229-4848",
        "Website": "balletmet.org/performances",
        "Time": "Call for times.",
        "Price": "$25�$60"
    },
    {
        "Region": "Central",
        "Category": "Music/Theater",
        "StartDate": "2/21/2020",
        "EndDate": "2/23/2020",
        "Title": "Joseph and the Amazing Technicolor Dreamcoat",
        "Description": "The biblical saga of Joseph and his coat of many colors comes to vibrant life in this delightful musical parable. Set to an engaging cornucopia of musical styles, from country-western and calypso to bubble-gum pop and rock 'n' roll, this Old Testament tal",
        "Venue": "Marion Palace Theatre",
        "Address": "276 W. Center St.",
        "City": "Marion",
        "Phone": "740/383-2101",
        "Website": "marionpalace.org",
        "Time": "Fri.�Sat. 7:30 p.m., Sun. 2 p.m.",
        "Price": "Adults $17�$22, children 12 and under $12"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "2/2/2020",
        "EndDate": "2/2/2020",
        "Title": "Ground Hog Day - Buckeye Chuck",
        "Description": "Buckeye Chuck is Ohio's official weather-predicting groundhog and will check for his shadow. Come early before the sun comes up, if any, to see Chuck. Always hot drinks and the spam burger that is served every year.",
        "Venue": "Clear Channel Marion",
        "Address": "1330 N. Main St.",
        "City": "Marion",
        "Phone": "740/383-1131",
        "Website": "wmrn.com",
        "Time": "7�8 a.m.",
        "Price": "Free"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "2/6/2020",
        "EndDate": "2/6/2020",
        "Title": "Fireside Chat - \"Doc\" Harding: Colorful Patriarch",
        "Description": "Second of three programs in the Guthery Room presented by Harding Home Presidential site.",
        "Venue": "Ohio State University Marion",
        "Address": "1465 Mt. Vernon Ave.",
        "City": "Marion",
        "Phone": "740/387-9630",
        "Website": "hardinghome.org",
        "Time": "7 p.m.",
        "Price": "$10�$25 for all three programs."
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "2/13/2020",
        "EndDate": "2/13/2020",
        "Title": "Fireside Chats - Phoebe Harding: Gentle Fortitude",
        "Description": "Third program of the Fireside Chats in the Guthery Room presented by Harding Home Presidential site.",
        "Venue": "Ohio State University Marion",
        "Address": "1465 Mt. Vernon Ave.",
        "City": "Marion",
        "Phone": "740/387-9630",
        "Website": "hardinghome.org",
        "Time": "7 p.m.",
        "Price": "$10�$25 for all three programs."
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "2/14/2020",
        "EndDate": "2/16/2020",
        "Title": "OEFFA's 35th Annual Conference: Affirming Our Roots, Breaking New Ground",
        "Description": "OEFFA's two-day conference is Ohio's largest sustainable agriculture event, featuring keynote speakers Kathleen Merrigan and Atina Diffley.",
        "Venue": "Granville Middle and High Schools",
        "Address": "248 New Burg St.",
        "City": "Granville",
        "Phone": "614/421-2022",
        "Website": "oeffa.org/conference2020",
        "Time": "All Day Event",
        "Price": "Call for prices."
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "2/16/2020",
        "EndDate": "2/16/2020",
        "Title": "Annual Bridal Show",
        "Description": "Make all of your bridal plans in one day. A style show will be held at 3 p.m.",
        "Venue": "All Occasions Banquet & Catering Facility",
        "Address": "6989 Waldo-Delaware Ave.",
        "City": "Waldo",
        "Phone": "740/726-2008",
        "Website": "classealloccasions.com",
        "Time": "1�4 p.m.",
        "Price": "$2"
    },
    {
        "Region": "Northeast",
        "Category": "Museums/Galleries",
        "StartDate": "2/16/2020",
        "EndDate": "5/11/2020",
        "Title": "Remaking Tradition: Modern Art of Japan",
        "Description": "Over 50 masterpieces of modern Japanese art from the Tokyo National Museum include six objects considered 'Important Cultural Properties of Japan.'",
        "Venue": "Cleveland Museum of Art",
        "Address": "11150 East Blvd.",
        "City": "Cleveland",
        "Phone": "216/421-7350",
        "Website": "clevelandart.org",
        "Time": "Tues., Thur., Sat. & Sun. 10 a.m.�5 p.m., Wed. & Fri. 10 a.m.�9 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Northeast",
        "Category": "Museums/Galleries",
        "StartDate": "2/15/2020",
        "EndDate": "2/15/2020",
        "Title": "Love Is Eternal",
        "Description": "Letters of selected Presidents & First Ladies are presented in a program that will be a living history Valentine.  After the program step around the corner to Bender's to continue the evening with a fantastic dinner. Call for reservations & dinner selecti",
        "Venue": "National First Ladies' Library",
        "Address": "205 Market Ave. S.",
        "City": "Canton",
        "Phone": "330/452-0876",
        "Website": "firstladies.org",
        "Time": "3:30 p.m.�7 p.m.",
        "Price": "$88 (for two), $79 members (for two)"
    },
    {
        "Region": "Northeast",
        "Category": "Music/Theater",
        "StartDate": "2/6/2020",
        "EndDate": "2/6/2020",
        "Title": "Gil Shaham, Solo Violin",
        "Description": "The violinist's combination of flawless technique with inimitable warmth and a generosity of spirit have solidified his legacy as an American master. The New York Times called him �one of today�s preeminent violinists.\"",
        "Venue": "Gartner Auditorium, Cleveland Museum of Art",
        "Address": "11150 East Blvd.",
        "City": "Cleveland",
        "Phone": "216/421-7350",
        "Website": "clevelandart.org",
        "Time": "7:30 p.m.",
        "Price": "$39�$59"
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "2/12/2020",
        "EndDate": "2/16/2020",
        "Title": "Cirque du Soleil - Varekai",
        "Description": "Cirque du Soleil brings its newest arena show to downtown Youngstown. You won't want to miss the mesmerizing acrobatic artistry.",
        "Venue": "Covelli Centre",
        "Address": "229 E. Front St.",
        "City": "Youngstown",
        "Phone": "330/746-5600",
        "Website": "covellicentre.com",
        "Time": "Wed.�Fri. 7:30 p.m., Sat. 4 & 7:30 p.m., Sun. 1:30 & 5 p.m.",
        "Price": "$28�$140"
    },
    {
        "Region": "Northeast",
        "Category": "Music/Theater",
        "StartDate": "2/14/2020",
        "EndDate": "3/9/2020",
        "Title": "Breath & Imagination",
        "Description": "Before the inspiring voices of Marian Anderson and Paul Robeson, there was an African-American tenor named Roland Hayes. This musical tale of faith, hope, and family traces a remarkable journey from rural Georgia to Carnegie Hall and Buckingham Palace.",
        "Venue": "Allen Theatre at PlayhouseSquare",
        "Address": "1407 Euclid Ave.",
        "City": "Cleveland",
        "Phone": "216/241-6000",
        "Website": "clevelandplayhouse.com/main-stage/2019-2020/breath-and-imagination",
        "Time": "Check website for times.",
        "Price": "$69�$15"
    },
    {
        "Region": "Northeast",
        "Category": "Music/Theater",
        "StartDate": "2/15/2020",
        "EndDate": "2/15/2020",
        "Title": "Youngstown Symphony Orchestra-Pops Concert: Broadway In Love",
        "Description": "The YSO will perform a compilation of obvious and not-so-obvious love songs from the Great White Way.\nEnjoy an evening of wonderful music in beautiful, historic Powers Auditorium-DeYor Perofrming Arts Center.",
        "Venue": "Powers Auditorium - DeYor Performing Arts Center",
        "Address": "260 W. Federal St.",
        "City": "Youngstown",
        "Phone": "330/744-0264",
        "Website": "youngstownsymphony.com",
        "Time": "8 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "2/6/2020",
        "EndDate": "2/6/2020",
        "Title": "Blind Date Menu",
        "Description": "Guests will be served a five course dinner, each course paired with an appropriate wine or cocktail. Similar to a blind date, the evening will unfold as each course is revealed. Advance reservations required.",
        "Venue": "Crosswinds Grille",
        "Address": "5653 Lake Rd. E",
        "City": "Geneva",
        "Phone": "440/466-8668",
        "Website": "",
        "Time": "Call for times.",
        "Price": "$75 (+tax) includes dinner, wine and gratuity."
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "2/8/2020",
        "EndDate": "2/8/2020",
        "Title": "Wayne County Farm Toy Show",
        "Description": "Farm toy show with vendors offering new and collectible farm toys and related items.  Smithville Future Farmers of America event and fundraiser.",
        "Venue": "Greene Middle School",
        "Address": "484 E. Main St.",
        "City": "Smithville",
        "Phone": "330/669-9455",
        "Website": "",
        "Time": "9 a.m.�3 p.m.",
        "Price": "Adults $2, children 10 and under free when accompanied by adult."
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "2/14/2020",
        "EndDate": "2/15/2020",
        "Title": "Buckeye Tool Show",
        "Description": "This two-day event draws over 120 different vendor displays. Join the excitement in Wayne County and shake the winter blues.",
        "Venue": "Buckeye Event Center",
        "Address": "624 Henry St.",
        "City": "Dalton",
        "Phone": "330/828-2466",
        "Website": "buckeyeexpo.com",
        "Time": "Fri. 8 a.m.�7 p.m., Sat. 8 a.m.�2:30 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "2/22/2020",
        "EndDate": "2/22/2020",
        "Title": "Ohio Bluebird Society Conference",
        "Description": "This year's theme for the annual educational conference is \"Finding Your Happiness in Nature: The Domino Effect of Bluebirding.\" State-of-the-art information and approaches to bluebirds are featured.",
        "Venue": "Fisher Auditorium, OARDC",
        "Address": "1680 Madison Ave.",
        "City": "Wooster",
        "Phone": "330/465-6987",
        "Website": "ohiobluebirdsociety.org",
        "Time": "8 a.m.�3:30 p.m.",
        "Price": "Free if pre�registered, walk�ins $5, $10 for pre�registered box lunch"
    },
    {
        "Region": "Northwest",
        "Category": "Fairs/Festivals",
        "StartDate": "2/1/2020",
        "EndDate": "2/1/2020",
        "Title": "An Ice-A-Fair to Remember",
        "Description": "Professionally carved ice sculptures and ice sculpting demos take over downtown Vermilion. Lolly the Trolley rides available.",
        "Venue": "Downtown",
        "Address": "Main Street and Liberty Avenue",
        "City": "Vermilion",
        "Phone": "440/963-0772",
        "Website": "mainstreetvermilion.org",
        "Time": "11 a.m.�4 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Northwest",
        "Category": "Fairs/Festivals",
        "StartDate": "2/1/2020",
        "EndDate": "2/2/2020",
        "Title": "Arctic Ice Festival",
        "Description": "Ice sculpture display, amateur ice carving competition, soup cook-off, ice boat races, children's activities, ice fishing and ice rescue demonstrations are among the fun activities, weather permitting.",
        "Venue": "Maritime Museum of Sandusky",
        "Address": "125 Meigs St.",
        "City": "Sandusky",
        "Phone": "419/624-0274",
        "Website": "sanduskymaritime.org",
        "Time": "10 a.m.�4 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Northwest",
        "Category": "Museums/Galleries",
        "StartDate": "2/13/2020",
        "EndDate": "5/11/2020",
        "Title": "The Art of the Louvre's Tuileries Garden",
        "Description": "This major exhibition explores the art, design and evolution of Paris� famed Tuileries Garden and its impact on such artists as Camille Pissarro and Childe Hassam. It also celebrates garden designer Andr� Le N�tre.",
        "Venue": "Toledo Museum of Art",
        "Address": "2445 Monroe St.",
        "City": "Toledo",
        "Phone": "419/255-8000",
        "Website": "toledomuseum.org",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "2/6/2020",
        "EndDate": "2/9/2020",
        "Title": "Rock of Ages",
        "Description": "In 1987 on the Sunset Strip, a small-town girl met a big-city rocker and they fell in love to the greatest songs of the '80s. This love story is told through the hits of Journey, Styx, REO Speedwagon, Pat Benatar and more.",
        "Venue": "Stranahan Theater",
        "Address": "4645 Heatherdowns Blvd.",
        "City": "Toledo",
        "Phone": "419/381-8851",
        "Website": "theaterleague.com/toledo/rock-of-ages/",
        "Time": "Call for times.",
        "Price": "Starts at $33."
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "2/15/2020",
        "EndDate": "2/15/2020",
        "Title": "A Night at the Oscars",
        "Description": "Symphonic music brings the films we love to life. This gem of a production features the members of the Toledo Symphony presenting awards for �Best Film Score.�",
        "Venue": "Stranahan Theater",
        "Address": "4645 Heatherdowns Blvd.",
        "City": "Toledo",
        "Phone": "419/246-8000",
        "Website": "stranahantheater.org",
        "Time": "8 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "2/28/2020",
        "EndDate": "2/28/2020",
        "Title": "The Brahms Project",
        "Description": "The first concert in a two part series featuring Brahms as well as Schubert.",
        "Venue": "Peristyle at the Toledo Museum of Art",
        "Address": "2445 Monroe St.",
        "City": "Toledo",
        "Phone": "419/246-8000",
        "Website": "toledosymphony.com",
        "Time": "8 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Southeast",
        "Category": "Music/Theater",
        "StartDate": "2/1/2020",
        "EndDate": "2/1/2020",
        "Title": "John Gorka",
        "Description": "See the contemporary American folk singer-songrwriter in concert.",
        "Venue": "Stuart's Opera House",
        "Address": "52 Public Square",
        "City": "Nelsonville",
        "Phone": "740/753-1924",
        "Website": "stuartsoperahouse.org",
        "Time": "8 p.m.",
        "Price": "$20�$30"
    },
    {
        "Region": "Southeast",
        "Category": "Music/Theater",
        "StartDate": "2/5/2020",
        "EndDate": "2/5/2020",
        "Title": "Rock of Ages",
        "Description": "Set in Hollywood's infamous Sunset Strip, this rock musical takes you back to when it was all about big chords, big dreams and big hair.",
        "Venue": "Southern Ohio Performing Arts Association",
        "Address": "940 Second St.",
        "City": "Portsmouth",
        "Phone": "740/351-3272",
        "Website": "sopaa.org",
        "Time": "7:30�9:30 p.m.",
        "Price": "$55"
    },
    {
        "Region": "Southeast",
        "Category": "Music/Theater",
        "StartDate": "2/18/2020",
        "EndDate": "2/18/2020",
        "Title": "Haifa Symphony Orchestra of Israel",
        "Description": "The Haifa Symphony Orchestra of Israel is the focal point of musical life in Haifa and the north of Israel. They will be playing music by Weber, Dvorak and a piano concerto by Tchaikovsky. This concert is the third event in the ZCA 75th Diamond Anniversar",
        "Venue": "Secrest Auditorium",
        "Address": "334 Shinnick St.",
        "City": "Zanesville",
        "Phone": "740/588-0871",
        "Website": "zanesvilleconcertassociation.com",
        "Time": "7 p.m.",
        "Price": "Adults $65, students $20 "
    },
    {
        "Region": "Southeast",
        "Category": "Other Events",
        "StartDate": "2/7/2020",
        "EndDate": "2/7/2020",
        "Title": "Brown Baggin' Thru History",
        "Description": "David Simmons will speak on bringing the canals to Ohio, looking at the mind-set of key figures and development.",
        "Venue": "Campus Martius Museum",
        "Address": "601 Second St.",
        "City": "Marietta",
        "Phone": "740/373-3750",
        "Website": "campusmartiusmuseum.org",
        "Time": "Noon",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "2/7/2020",
        "EndDate": "5/18/2020",
        "Title": "Threads of Heaven: Silken Legacy of China's Last Dynasty",
        "Description": "Rarely seen imperial silk robes, hats, fans and more make up the selection of exquisitely embellished robes, accessories and textiles from the Qing dynasty.",
        "Venue": "Taft Museum of Art",
        "Address": "316 Pike St.",
        "City": "Cincinnati",
        "Phone": "513/241-0343",
        "Website": "taftmuseum.org",
        "Time": "Call for times.",
        "Price": "Adults $10, seniors and students $8, children 12�17 $4, children under 12 free"
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "2/14/2020",
        "EndDate": "8/17/2020",
        "Title": "Diana: A Celebration",
        "Description": "See the life and humanitarian work of Princess Diana through nine galleries containing 150 objects ranging from her royal wedding gown and 28 of her designer dresses to rare home movies and videos.",
        "Venue": "Cincinnati Museum Center",
        "Address": "1301 Western Ave.",
        "City": "Cincinnati",
        "Phone": "513/287-7000",
        "Website": "cincymuseum.org",
        "Time": "Mon.�Tues. noon�6 p.m., Wed.�Fri. noon�8 p.m., Sat.�Sun. 11 a.m.�8 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Southwest",
        "Category": "Museums/Galleries",
        "StartDate": "2/22/2020",
        "EndDate": "5/18/2020",
        "Title": "From the Village to Vogue: The Modernist Jewelry of Art Smtih",
        "Description": "Inspired by surrealism, biomorphism, and primitivism, African-American artist Art Smith was one of the leading modernist jewelers of the mid-twentieth century.",
        "Venue": "Cincinnati Museum of Art",
        "Address": "953 Eden Park Dr.",
        "City": "Cincinnati",
        "Phone": "513/721-ARTS",
        "Website": "cincinnatiartmuseum.org",
        "Time": "Tues.�Sun. 11 a.m.�5 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "2/1/2020",
        "EndDate": "2/1/2020",
        "Title": "Hotel California - Eagles Tribute",
        "Description": "The original tribute to The Eagles draws crowds of all ages with different musical styles. The Eagles' great harmonies have been enjoyed by audiences across the world.",
        "Venue": "Murphy Theatre",
        "Address": "50 W. Main St.",
        "City": "Wilmington",
        "Phone": "877/274-3848",
        "Website": "http://themurphytheatre.org",
        "Time": "7:30 p.m.",
        "Price": "$22."
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "2/6/2020",
        "EndDate": "2/6/2020",
        "Title": "Re:member",
        "Description": "Concert:nova presents a stirring program of chamber music written before, during and after the Great War, each piece paints a picture of the human spirit during one of the bloodiest wars in human history.",
        "Venue": "The Carnegie",
        "Address": "1028 Scott Blvd.",
        "City": "Covington",
        "Phone": "513/739-NOVA (6682)",
        "Website": "concertnova.com",
        "Time": "8 p.m.",
        "Price": "$25 adult, $12 student."
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "2/6/2020",
        "EndDate": "2/9/2020",
        "Title": "Metamorphoses",
        "Description": "This entrancing re-telling of Ovid's myths offers breathtaking storytelling and an escape from the ordinary that dares to brush with the divine. For mature audiences only.",
        "Venue": "Patricia Corbett Theater",
        "Address": "University of Cincinnati",
        "City": "Cincinnati",
        "Phone": "513/556-4183",
        "Website": "ccm.uc.edu",
        "Time": "Thur.�Fri. 8 p.m., Sat. 2 & 8 p.m., Sun. 2 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "2/8/2020",
        "EndDate": "2/8/2020",
        "Title": "Renfro Valley Barn Show",
        "Description": "This variety show of talent comes complete with artists proficient in country, bluegrass, gospel and more.",
        "Venue": "Murphy Theatre",
        "Address": "50 W. Main St.",
        "City": "Wilmington",
        "Phone": "877/274-3848",
        "Website": "http://themurphytheatre.org",
        "Time": "7:30 pm",
        "Price": "$22.50"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "2/14/2020",
        "EndDate": "2/14/2020",
        "Title": "Wild Carrot",
        "Description": "This Cincinnati-based, award-winning group has what it takes to please all types of folk music fans. Rooted in traditional American music, their repertoire branches in diverse directions from original tunes to swing to blues.",
        "Venue": "Murphy Theatre",
        "Address": "50 W. Main St.",
        "City": "Wilmington",
        "Phone": "877/274-3848",
        "Website": "http://themurphytheatre.org",
        "Time": "7:30 p.m.",
        "Price": "$15"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "2/16/2020",
        "EndDate": "2/16/2020",
        "Title": "Pianopalooza IX",
        "Description": "Celebrate the art of the piano with the ninth installment of this popular concert, showcasing CCM's most spectacular student pianists.",
        "Venue": "Patricia Corbett Theater",
        "Address": "University of Cincinnati",
        "City": "Cincinnati",
        "Phone": "513/556-4183",
        "Website": "ccm.uc.edu",
        "Time": "7 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "2/27/2020",
        "EndDate": "3/9/2020",
        "Title": "Les Miserables",
        "Description": "Victor Hugo's saga of one man's lifelong quest for redemption continues to sweep audiences of their feet.",
        "Venue": "Patricia Corbett Theater",
        "Address": "University of Cincinnati",
        "City": "Cincinnati",
        "Phone": "513/556-4183",
        "Website": "ccm.uc.edu",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Southwest",
        "Category": "Other Events",
        "StartDate": "2/7/2020",
        "EndDate": "3/20/2020",
        "Title": "Abraham Lincoln: The Constitution and the Civil War",
        "Description": "National traveling exhibit that looks at the constitutional issues faced by President Lincoln, including secession of Southern states, slavery and wartime civil liberties.",
        "Venue": "Swedenborg Memorial Library, Urbana University",
        "Address": "579 College Way",
        "City": "Urbana",
        "Phone": "937/484-1409",
        "Website": "urbana.edu/",
        "Time": "Mon.�Thur. 8 a.m.�9 p.m., Fri. 8 a.m.�4 p.m., Sat. 12�4 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Other Events",
        "StartDate": "2/12/2020",
        "EndDate": "2/12/2020",
        "Title": "Lincoln and the Problem of Freedom",
        "Description": "Brown bag discussion of Abraham Lincoln's issues with slavery and the Emancipation Proclamation.  Presented in conjunction with Urbana University's Abraham Lincoln: The Civil War and the Constitution exhibit.",
        "Venue": "Urbana University Library",
        "Address": "579 College Way",
        "City": "Urbana",
        "Phone": "937/484-1335",
        "Website": "http://urbana.edu/resources/community/Lincoln2020.html",
        "Time": "Noon�1 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Other Events",
        "StartDate": "2/23/2020",
        "EndDate": "2/23/2020",
        "Title": "The Long and Short of It:  Lincoln's Relationship with Alexander Stephens",
        "Description": "Abraham Lincoln enjoyed a friendly relationship with Confederate Vice President Stephens. In this illustrated talk, Dr. Randall Buchman examines their relationship, their shared opposition to secession, and considers an unusual presidential pardon with an",
        "Venue": "Urbana University Library",
        "Address": "579 College Way",
        "City": "Urbana",
        "Phone": "937/484-1335",
        "Website": "http://urbana.edu/resources/community/Lincoln2020.html",
        "Time": "2�3 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Central",
        "Category": "Museums/Galleries",
        "StartDate": "3/28/2020",
        "EndDate": "3/29/2020",
        "Title": "Night At The Museum",
        "Description": "Imagine roaming the halls of the once US Post Office with only a flash light to guide you. Historical characters come to life around every corner. Children must be accompanied by an adult.",
        "Venue": "Heritage Hall",
        "Address": "169 E. Church St.",
        "City": "Marion",
        "Phone": "740/387-4255",
        "Website": "marionhistory.com",
        "Time": "7�9:30 p.m.",
        "Price": "non�members $7, at door $8; members $3.50, at door $4"
    },
    {
        "Region": "Central",
        "Category": "Museums/Galleries",
        "StartDate": "3/8/2020",
        "EndDate": "9/28/2020",
        "Title": "Blooms and Butterflies",
        "Description": "Hundreds of colorful, exotic butterflies fly freely in the Pacific Island Water Garden, a warm and tropical haven filled with bright nectar blooms. A new children's interactive area opens.",
        "Venue": "Franklin Park Conservatory",
        "Address": "1777 E. Broad St.",
        "City": "Columbus",
        "Phone": "614/715-8000",
        "Website": "fpconservatory.org",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Central",
        "Category": "Music/Theater",
        "StartDate": "3/14/2020",
        "EndDate": "3/14/2020",
        "Title": "Five Nights On Campus - Wild Carrot & The Roots Band",
        "Description": "Pam Temple and Spencer Funk met through music, married and began performing together full time in 2000 as Wild Carrot. They were named \"Best Folk Act\" in their hometown of Cincinnati and have crisscrossed the country with an eclectic mix of award-winning ",
        "Venue": "Ohio State University Marion",
        "Address": "1465 Mt. Vernon Ave.",
        "City": "Marion",
        "Phone": "740/725-6253",
        "Website": "osumarion.osu.edu",
        "Time": "7:30 p.m.",
        "Price": "Adults $10, seniors $9, students $4."
    },
    {
        "Region": "Central",
        "Category": "Music/Theater",
        "StartDate": "3/21/2020",
        "EndDate": "3/23/2020",
        "Title": "BalletMet's Symphony in C",
        "Description": "Set to Bizet's exuberant score, a cast of dancers from BalletMet and Cincinnati Ballet gather on stage together. Also on the program is Victoria Morgan's \"Bolero\" set to Maurice Ravel's famous score. Rounding out this ravishing program is a company premie",
        "Venue": "The Ohio Theatre",
        "Address": "39 E. State St.",
        "City": "Columbus",
        "Phone": "614/229-4848",
        "Website": "balletmet.org/performances",
        "Time": "Call for times.",
        "Price": "$25�$80"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "3/8/2020",
        "EndDate": "3/8/2020",
        "Title": "Annual Hobbies on Display",
        "Description": "Marion Whetstone Woodcarvers and the Marion Hobby Club presents raffles, a woodcarving demonstration and more than 50 display tables.",
        "Venue": "John M. Boler Activity Center",
        "Address": "1001 Mt. Vernon Ave.",
        "City": "Marion",
        "Phone": "740/465-4193",
        "Website": "",
        "Time": "10 a.m.�5 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "3/20/2020",
        "EndDate": "3/20/2020",
        "Title": "WELD 2020 Keynote Susan Packard",
        "Description": "WELD is featuring Susan Packard, as she shares her insight on \"The Leader With: Growing Your Leadership Team.\" Co-founder executive behind CNBC, HGTV, Food Network and other popular cable channels, her approach to leadership & innovation has helped her bu",
        "Venue": "Hilton Downtown Columbus",
        "Address": "401 N. High St.",
        "City": "Columbus",
        "Phone": "614/890-2586",
        "Website": "",
        "Time": "5:45�8:30 p.m.",
        "Price": "$100 members, $125 non�members"
    },
    {
        "Region": "Central",
        "Category": "Other Events",
        "StartDate": "3/29/2020",
        "EndDate": "3/29/2020",
        "Title": "Spring Garden & Home Show",
        "Description": "Get an early start on Spring. Featured speaker Ron Wilson, host of the radio show \"In The Garden With Ron\" will be available to answer your questions.",
        "Venue": "Tri-Rivers Career Center",
        "Address": "2222 Marion-Mt. Gilead Rd.",
        "City": "Marion",
        "Phone": "740/389-9770",
        "Website": "",
        "Time": "10 a.m.�5 p.m.",
        "Price": "$5"
    },
    {
        "Region": "Northeast",
        "Category": "Museums/Galleries",
        "StartDate": "3/2/2020",
        "EndDate": "5/26/2020",
        "Title": "Van Gogh Repetitions",
        "Description": "The ground-breaking exhibition will present new insights into the art of Vincent van Gogh through a study of his �repetitions,� a term the artist used to describe a distinctive genre of his works. ",
        "Venue": "Cleveland Museum of Art",
        "Address": "11150 East Blvd.",
        "City": "Cleveland",
        "Phone": "216/421-7350",
        "Website": "clevelandart.org",
        "Time": "Tues., Thur., Sat. & Sun. 10 a.m.�5 p.m., Wed. & Fri. 10 a.m.�9 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Northeast",
        "Category": "Museums/Galleries",
        "StartDate": "3/22/2020",
        "EndDate": "3/22/2020",
        "Title": "Vinnie Ream: A Teenage Artist's \"Labor of Love\" Tea",
        "Description": "Vinnie Ream became famous when her white marble sculpture of President Lincoln was unveiled in the US Capitol building in January 1871. The multi-talented artist will share tales of her unique career & how she was the first woman sculptor to receive a gov",
        "Venue": "National First Ladies' Library",
        "Address": "205 Market Ave. S.",
        "City": "Canton",
        "Phone": "330/452-0876",
        "Website": "firstladies.org",
        "Time": "Call for times.",
        "Price": "$31 members, $35 general admission"
    },
    {
        "Region": "Northeast",
        "Category": "Music/Theater",
        "StartDate": "3/15/2020",
        "EndDate": "3/15/2020",
        "Title": "Youngstown Symphony Orchestra-Masterworks Concert",
        "Description": "The YSO will salute Celtic heritage with Maxwell Davies' \"An Orkney Wedding\" and Bruch's \"Scottish Fantasy,\" featuring violinist Timothy Fain. Mendelssohn's Symphony No. 3  \"Scottish\" is also on the program.\nEnjoy an evening of wonderful music in beautifu",
        "Venue": "Powers Auditorium - DeYor Performing Arts Center",
        "Address": "260 W. Federal St.",
        "City": "Youngstown",
        "Phone": "330/744-0264",
        "Website": "youngstownsymphony.com",
        "Time": "8 p.m.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northeast",
        "Category": "Music/Theater",
        "StartDate": "3/28/2020",
        "EndDate": "4/6/2020",
        "Title": "Arsenic & Old Lace - The Youngstown Playhouse",
        "Description": "The classic comedy that kills with kindness. Spinster sisters Abby and Martha Brewster are devoted to charity and family, but they have taken on another project as well: befriending lonely older gentlemen and then poisoning them with arsenic-laced elderbe",
        "Venue": "The Youngstown Playhouse",
        "Address": "600 Playhouse Ln.",
        "City": "Youngstown",
        "Phone": "330/788-8739",
        "Website": "theyoungstownplayhouse.com",
        "Time": "Call for times.",
        "Price": "Call for prices."
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "3/1/2020",
        "EndDate": "3/2/2020",
        "Title": "Dave & Ed's Super Auto Events Pro-Formance Swap Meet",
        "Description": "Ohio's largest Indoor/Outdoor performance meet! Vendors selling circle track, drag, sprint and street wares.",
        "Venue": "Stark County Fairgrounds",
        "Address": "305 Wertz Ave. NW",
        "City": "Canton",
        "Phone": "330/477-8506",
        "Website": "autoevents.com",
        "Time": "8 a.m.�4 p.m.",
        "Price": "$7 day pass, $10 weekend pass, children 11 and under free."
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "3/8/2020",
        "EndDate": "3/9/2020",
        "Title": "McKinley Stamp Club 83rd Stamp Show",
        "Description": "Twenty stamp dealers buying and selling postage stamps, covers and postcards.  Stamp exhibits included.",
        "Venue": "St. George Serbian Orthodox Social Hall",
        "Address": "4667 Applegrove St. N.W.",
        "City": "North Canton",
        "Phone": "330/832-5992",
        "Website": "mksc.webs.com",
        "Time": "10 a.m.�4 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Northeast",
        "Category": "Other Events",
        "StartDate": "3/14/2020",
        "EndDate": "3/16/2020",
        "Title": "Cleveland Home + Remodeling Expo",
        "Description": "The new Cleveland Home + Remodeling Expo will bring remodeling, renovation and design inspiration to the Cleveland Convention Center.",
        "Venue": "Cleveland Convention Center",
        "Address": "500 Lakeside Ave.",
        "City": "Cleveland",
        "Phone": "888/248-9751",
        "Website": "homeandremodelingexpo.com",
        "Time": "Fri. noon–9 p.m.,  Sat. 10 a.m.–9 p.m., Sun. 10 a.m.–6 p.m.",
        "Price": "$10"
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "3/2/2020",
        "EndDate": "3/4/2020",
        "Title": "American Idiot",
        "Description": "Told through the music of rock band Green Day, \"American Idiot\" tells the story of three lifelong friends who are forced to choose between their dreams and the safety of suburbia.",
        "Venue": "Stranahan Theater",
        "Address": "4645 Heatherdowns Blvd.",
        "City": "Toledo",
        "Phone": "419/381-8851",
        "Website": "theaterleague.com/toledo/american-idiot/",
        "Time": "Call for times.",
        "Price": "Tickets start at $38."
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "3/9/2020",
        "EndDate": "3/9/2020",
        "Title": "Broadway Hair!",
        "Description": "The Public Theater's new Tony Award-winning production of HAIR is an exuberant musical about a group of young Americans searching for peace and love in a turbulent time has struck a resonant chord with audiences young and old.",
        "Venue": "Veterans Memorial Civic & Convention Center",
        "Address": "7 Town Square",
        "City": "Lima",
        "Phone": "419/224-1552",
        "Website": "limaciviccenter.com",
        "Time": "7 p.m.",
        "Price": "$60.00"
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "3/20/2020",
        "EndDate": "3/23/2020",
        "Title": "Million Dollar Quartet",
        "Description": "This Tony Award-winning musical is inspired by the famed recording session that brought rock icons Elvis Presley, Johnny Cash, Jerry Lee Lewis and Carl Perkins together for what would be one of the greatest jam sessions of all time.",
        "Venue": "Stranahan Theater",
        "Address": "4645 Heatherdowns Blvd.",
        "City": "Toledo",
        "Phone": "419/381-8851",
        "Website": "theaterleague.com/toledo/million-dollar-quartet/",
        "Time": "Call for times.",
        "Price": "Starts at $28."
    },
    {
        "Region": "Northwest",
        "Category": "Music/Theater",
        "StartDate": "3/21/2020",
        "EndDate": "3/21/2020",
        "Title": "Broadway \"Momma Mia\"",
        "Description": "Over 45 million people all around the world have fallen in love with the characters, the story and the music that make MAMMA MIA! the ultimate feel-good show. Writer Catherine Johnson's sunny, funny tale unfolds on a Greek island paradise.",
        "Venue": "Veterans Memorial Civic & Convention Center",
        "Address": "7 Town Square",
        "City": "Lima",
        "Phone": "419/224-1552",
        "Website": "limaciviccenter.com",
        "Time": "8 p.m.",
        "Price": "$68.50"
    },
    {
        "Region": "Southeast",
        "Category": "Music/Theater",
        "StartDate": "3/8/2020",
        "EndDate": "3/8/2020",
        "Title": "Broadway!",
        "Description": "Steve Amerson is known as America's Tenor for his depth of performance experience and work in over 160 feature films.",
        "Venue": "Ariel Ann Carson Dater Performing Arts Center",
        "Address": "426 Second Ave.",
        "City": "Gallipolis",
        "Phone": "740/446-ARTS",
        "Website": "arieltheatre.org",
        "Time": "8 p.m.",
        "Price": "$12�$24"
    },
    {
        "Region": "Southeast",
        "Category": "Music/Theater",
        "StartDate": "3/9/2020",
        "EndDate": "3/9/2020",
        "Title": "David Tolley, Pianist/Composer",
        "Description": "An afternoon with David Tolley will highlight Tolley's talents as pianist, composer and music producer. David has performed for four presidents and Johnny Carson on the \"Tonight Show.\"",
        "Venue": "Secrest Auditorium",
        "Address": "334 Shinnick St.",
        "City": "Zanesville",
        "Phone": "740/588-0871",
        "Website": "zanesvilleconcertassociation.com",
        "Time": "3 p.m.",
        "Price": "Adults $65, students $20"
    },
    {
        "Region": "Southeast",
        "Category": "Music/Theater",
        "StartDate": "3/23/2020",
        "EndDate": "3/23/2020",
        "Title": "Junior Music Club Festival Recital",
        "Description": "The Junior Music Club will showcase K-8 grade members in a Festival Recital. This music event is sponsored by the Thursday Music Club which is celebrating its 104th year of sponsoring local music concerts.",
        "Venue": "Elson Hall at Ohio University Zanesville",
        "Address": "1425 Newark Rd.",
        "City": "Zanesville",
        "Phone": "740/452-3241",
        "Website": "",
        "Time": "3 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southeast",
        "Category": "Music/Theater",
        "StartDate": "3/25/2020",
        "EndDate": "3/25/2020",
        "Title": "The Miracle Worker",
        "Description": "This show demonstrates to the world what love and devotion can accomplish, even in the blind and deaf world.",
        "Venue": "Southern Ohio Performing Arts Association",
        "Address": "940 Second St.",
        "City": "Portsmouth",
        "Phone": "740/351-3600",
        "Website": "sopaa.org",
        "Time": "7:30�9:30 p.m.",
        "Price": "$45"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "3/8/2020",
        "EndDate": "3/8/2020",
        "Title": "Fuego: 40th Anniversary Concert + Gala*",
        "Description": "Escape the chills of March for an evening infused with sultry Latin spices and hot rhythms that will have you dancing in the aisles. The Cincinnati Contemporary Jazz Orchestra and salsa band Tropicoso help the CCO turn up the heat.",
        "Venue": "Cincinnati Masonic Center",
        "Address": "317 E. 5th St.",
        "City": "Cincinnati",
        "Phone": "513/723-1182",
        "Website": "ccocincinnati.org",
        "Time": "7 p.m.",
        "Price": "$25, $10"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "3/15/2020",
        "EndDate": "3/15/2020",
        "Title": "Donn Piatt and Abraham Lincoln",
        "Description": "Actor Tony St. Clair portrays Donn Piatt as he tells the story of the relationship between the Lincolns and the Piatts, whose relationship was strained when Piatt recruited slaves to become Union soldiers.",
        "Venue": "Mac-A Cheek Castle",
        "Address": "10051 Township Rd. 47",
        "City": "West Liberty",
        "Phone": "937/484-1335",
        "Website": "http://urbana.edu/resources/community/Lincoln2020.html",
        "Time": "2�4 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "3/15/2020",
        "EndDate": "3/15/2020",
        "Title": "Strange, Quaint and Great: Reflections on Abraham Lincoln by Donn Piatt",
        "Description": "Actor Tony St. Clair portrays Donn Piatt, an Ohioan who campaigned for Lincoln, served under him as Colonel, and later described him in the book entitled, \"Memories of Men Who Saved the Union.\"",
        "Venue": "Mac-A Cheek Castle",
        "Address": "10051 Township Rd. 47",
        "City": "West Liberty",
        "Phone": "937/484-1335",
        "Website": "http://urbana.edu/resources/community/Lincoln2020.html",
        "Time": "2�4 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Music/Theater",
        "StartDate": "3/30/2020",
        "EndDate": "3/30/2020",
        "Title": "Ballet Toybox",
        "Description": "Learn about the essential elements that make up the inspiring discipline of dance with a range of excerpts from exciting ballets, and introduce young children to the joy of dance.",
        "Venue": "Aronoff Center",
        "Address": "650 Walnut St.",
        "City": "Cincinnati",
        "Phone": "513/621-5282",
        "Website": "cballet.org",
        "Time": "2 p.m.",
        "Price": "$20"
    },
    {
        "Region": "Southwest",
        "Category": "Other Events",
        "StartDate": "3/4/2020",
        "EndDate": "3/4/2020",
        "Title": "Nursing in the Civil War",
        "Description": "Join Associate Professor of Nursing Barbara Niville for a brown bag discussion about the role of nurses in the US Civil War.  Presented in conjunction with Urbana University's Abraham Lincoln: The Civil War and the Presidency exhibit.",
        "Venue": "Urbana University Library",
        "Address": "579 College Way",
        "City": "Urbana",
        "Phone": "937/484-1335",
        "Website": "http://urbana.edu/resources/community/Lincoln2020.html",
        "Time": "Noon�1 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Other Events",
        "StartDate": "3/18/2020",
        "EndDate": "3/18/2020",
        "Title": "The Day Lincoln Spent in Dayton",
        "Description": "Dayton historian Josh Cain will describe the places Abraham Lincoln visited and the people with whom he met when he visited Dayton in 1859.  Presented in conjunction with Urbana University's exhibit Abraham Lincoln: The Civil War and the Constitution.",
        "Venue": "Urbana University Library",
        "Address": "579 College Way",
        "City": "Urbana",
        "Phone": "937/484-1335",
        "Website": "urbana.edu/resources/community/Lincoln2020",
        "Time": "Noon�1 p.m.",
        "Price": "Free"
    },
    {
        "Region": "Southwest",
        "Category": "Other Events",
        "StartDate": "3/20/2020",
        "EndDate": "3/20/2020",
        "Title": "Lincoln's Funeral Train",
        "Description": "Scot Trostel, author and historian, will share the story of Lincoln's funeral train.  Due to concern about protestors, the train was diverted from its original stops and traveled through four Champaign County depots.",
        "Venue": "Urbana University Library",
        "Address": "579 College Way",
        "City": "Urbana",
        "Phone": "937/484-1335",
        "Website": "http://urbana.edu/resources/community/Lincoln2020.html",
        "Time": "7�8:30 p.m.",
        "Price": "Free"
    }
  ];

  public selectedEvent: QuestEvent;

  public filteredEvents: Subject<QuestEvent[]> = new Subject<QuestEvent[]>();

  public search(searchCriteria: SearchCriteria): void {
    let filteredEvents = this.events.filter(event => {
      const categoryMatch = searchCriteria.Category ? event.Category.toLowerCase().includes(searchCriteria.Category.toLowerCase()) : true;
      const startDateMatch = searchCriteria.StartDate ? new Date(event.StartDate) >= searchCriteria.StartDate : true;
      const endDateMatch = searchCriteria.EndDate ? new Date(event.EndDate) <= searchCriteria.EndDate : true;
      const cityMatch = searchCriteria.City ? event.City.toLowerCase().includes(searchCriteria.City.toLowerCase()) : true;
      const venueMatch = searchCriteria.Venue ? event.Venue.toLowerCase().includes(searchCriteria.Venue.toLowerCase()) : true;
      let keywordMatch = false;
      if (searchCriteria.Keyword) {
        for (const property in event) {
          if (event[property].toLowerCase().includes(searchCriteria.Keyword.toLowerCase())) {
            keywordMatch = true;
          }
        }
      }
      else {
        keywordMatch = true;
      }
      return categoryMatch && startDateMatch && endDateMatch && cityMatch && venueMatch && keywordMatch;
    });

    this.filteredEvents.next(filteredEvents);
  }

  constructor() { }

}
